os:
  - linux

dist: trusty

language: php

services:
  - mysql
  - redis

addons:
  mariadb: '10.0'

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

jobs:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=4.7

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mysql -u root -e 'CREATE DATABASE wordpress_unittest;'
  - mysql -u root -e "CREATE USER 'shieldon'@'localhost' IDENTIFIED BY 'taiwan';"
  - mysql -u root -e "GRANT ALL ON shieldon_unittest.* TO 'shieldon'@'localhost';"
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_unittest shieldon taiwan localhost $WP_VERSION false
      composer update
    fi
  - bash bin/copy-plugin.sh

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer test
      WP_MULTISITE=1
      composer test
    fi
